### ISSUE TITLE
Make active pages selected in all navs/links

### ISSUE THREAD

**Issue by goliatone** [goliatone/core.io-website#58]
Use CSS to have an active style for current page, something like this:

```html
<body class="home">
    <ul>
        <li class="home"><a href="index.html">Home</a>
        <li class="about"><a href="documentation.html">Documentation</a>
        <li class="contact"><a href="quickstart.html">Quickstart</a>
    </ul>
</body>
```

```css
body.home .home a,
body.documentation .documentation a,
body.documentation .documentation a{
	padding:10px;
	background:#FF0000;
	margin-right:5px;
	color:#FFFF00;
	text-decoration:none;
}
```
